--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 98, in <module>
    logger.info("PyTorch Version: %s" % (torch.__version__))
Message: 'PyTorch Version: 1.7.1'
Arguments: ()
2021-10-24 10:24:17,801 PyTorch Version: 1.7.1
--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 105, in <module>
    logger.info("GPU List: %s" % (device_list))
Message: "GPU List: ['Tesla V100-SXM2-32GB']"
Arguments: ()
2021-10-24 10:24:17,807 GPU List: ['Tesla V100-SXM2-32GB']
--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 114, in <module>
    logger.info("%s: %s" % (key, config[key]))
Message: 'num_classes: 10'
Arguments: ()
2021-10-24 10:24:17,811 num_classes: 10
--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 114, in <module>
    logger.info("%s: %s" % (key, config[key]))
Message: 'epochs: 300'
Arguments: ()
2021-10-24 10:24:17,812 epochs: 300
--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 114, in <module>
    logger.info("%s: %s" % (key, config[key]))
Message: 'grad_clip: 5.0'
Arguments: ()
2021-10-24 10:24:17,812 grad_clip: 5.0
--- Logging error ---
Traceback (most recent call last):
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1029, in emit
    self.flush()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/logging/__init__.py", line 1009, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "ssl_perturbation_save_model.py", line 114, in <module>
    logger.info("%s: %s" % (key, config[key]))
Message: 'log_frequency: 100'
Arguments: ()
2021-10-24 10:24:17,813 log_frequency: 100
