2021-11-01 15:58:56,840 PyTorch Version: 1.7.1
2021-11-01 15:58:56,862 GPU List: ['Tesla V100-SXM2-32GB']
2021-11-01 15:58:56,865 num_classes: 10
2021-11-01 15:58:56,865 epochs: 300
2021-11-01 15:58:56,866 grad_clip: 5.0
2021-11-01 15:58:56,866 log_frequency: 100
2021-11-01 15:58:56,867 model: {'name': 'ResNet18', 'num_classes': 10}
2021-11-01 15:58:56,867 criterion: {'name': 'CrossEntropyLoss'}
2021-11-01 15:58:56,867 optimizer: {'name': 'SGD', 'lr': 0.1, 'weight_decay': 0.0005, 'momentum': 0.9}
2021-11-01 15:58:56,868 scheduler: {'name': 'CosineAnnealingLR', 'T_max': 300, 'eta_min': 0.0}
2021-11-01 15:58:56,868 dataset: {'name': 'DatasetGenerator', 'train_batch_size': 128, 'eval_batch_size': 128}
Training images:   0%|          | 0/2 [00:00<?, ?it/s]Training images:   0%|          | 0/2 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "ssl_perturbation_save_model.py", line 838, in <module>
    main()
  File "ssl_perturbation_save_model.py", line 823, in main
    noise, save_name_pre = universal_perturbation(noise_generator, None, None, model, None, optimizer, None, random_noise, ENV, train_loader, train_noise_data_loader, batch_size, temperature, memory_loader, test_loader, k, train_data)
  File "ssl_perturbation_save_model.py", line 311, in universal_perturbation
    delta = torch.stack(class_noise_eta[key]).mean(dim=0) - random_noise[key]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
