2021-09-30 20:26:04,883 PyTorch Version: 1.7.1
2021-09-30 20:26:04,901 num_classes: 10
2021-09-30 20:26:04,902 epochs: 60
2021-09-30 20:26:04,902 grad_clip: 5.0
2021-09-30 20:26:04,903 log_frequency: 100
2021-09-30 20:26:04,903 model: {'name': 'ResNet18', 'num_classes': 10}
2021-09-30 20:26:04,903 criterion: {'name': 'CrossEntropyLoss'}
2021-09-30 20:26:04,904 optimizer: {'name': 'SGD', 'lr': 0.1, 'weight_decay': 0.0005, 'momentum': 0.9}
2021-09-30 20:26:04,904 scheduler: {'name': 'CosineAnnealingLR', 'T_max': 60, 'eta_min': 0.0}
2021-09-30 20:26:04,904 dataset: {'name': 'DatasetGenerator', 'train_batch_size': 128, 'eval_batch_size': 128}
2021-09-30 20:26:04,906 seed: 0
2021-09-30 20:26:04,906 version: resnet18
2021-09-30 20:26:04,907 exp_name: path/to/your/experiment/folder
2021-09-30 20:26:04,907 config_path: configs/cifar10
2021-09-30 20:26:04,907 load_model: False
2021-09-30 20:26:04,907 data_parallel: False
2021-09-30 20:26:04,908 train_batch_size: 512
2021-09-30 20:26:04,908 eval_batch_size: 512
2021-09-30 20:26:04,908 num_of_workers: 8
2021-09-30 20:26:04,909 train_data_type: CIFAR10
2021-09-30 20:26:04,909 train_data_path: ../datasets
2021-09-30 20:26:04,909 test_data_type: CIFAR10
2021-09-30 20:26:04,909 test_data_path: ../datasets
2021-09-30 20:26:04,910 universal_train_portion: 0.2
2021-09-30 20:26:04,910 universal_stop_error: 0.5
2021-09-30 20:26:04,910 universal_train_target: classwise
2021-09-30 20:26:04,911 train_step: 2
2021-09-30 20:26:04,911 use_subset: False
2021-09-30 20:26:04,911 attack_type: min-min
2021-09-30 20:26:04,911 perturb_type: classwise
2021-09-30 20:26:04,911 patch_location: center
2021-09-30 20:26:04,912 noise_shape: [10, 3, 32, 32]
2021-09-30 20:26:04,912 epsilon: 0.03137254901960784
2021-09-30 20:26:04,912 num_steps: 6
2021-09-30 20:26:04,912 step_size: 0.0031372549019607846
2021-09-30 20:26:04,913 random_start: False
2021-09-30 20:26:04,913 feature_dim: 128
2021-09-30 20:26:04,913 temperature: 0.5
2021-09-30 20:26:04,914 k: 200
2021-09-30 20:26:04,914 batch_size: 512
2021-09-30 20:26:04,914 epochs: 500
2021-09-30 20:26:04,915 arch: resnet18
2021-09-30 20:26:04,915 noise_num: 10
Traceback (most recent call last):
  File "ssl_perturbation.py", line 599, in <module>
    main()
  File "ssl_perturbation.py", line 540, in main
    model = Model(feature_dim, arch=args.arch).cuda()
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 359, in _apply
    module._apply(fn)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in _apply
    param_applied = fn(param)
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/mnt/home/renjie3/miniconda3/envs/simclr/lib/python3.7/site-packages/torch/cuda/__init__.py", line 172, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
